### ISSUE TITLE
ICUAS 24 competition installation problems

### ISSUE THREAD

**Issue by fpetric** [larics/icuas24_competition#14]
### Discussed in https://github.com/larics/icuas24_competition/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **medini-sr** January  4, 2024</sup>
when i tried to clone the github repository after setting up the workspace i got an error which said i dont have the access rights to clone it .The screenshot regarding the same is attached below.Please help us sort this issue out.
![Screenshot from 2024-01-04 19-11-55](https://github.com/larics/icuas23_competition/assets/117924750/1c803a40-dac1-474b-b3bc-3b47b2e03b4b)
</div>

**Comment by fpetric** [comment]
Just to make sure, you are installing via the instructions from the ICUAS'24 Competition readme? (this repo?)

**Comment by medini-sr** [comment]
yes i am following the Advanced instruction on the https://github.com/larics/uav_ros_simulation 
After I clone the repository and try to run  the install.sh, i am getting this error.

**Comment by lmark1** [comment]
The native installation of **uav_ros_simulation** is no longer available due to restricted permissions to certain repositories. 
The preferred and easiest method is to simply build the Docker (in **icuas24_competition** repository) by running
```bash
./docker_build.sh
```
