### ISSUE TITLE
Problem with manually installing UAV software stack from uav_ros_simulation

### ISSUE THREAD

**Issue by fpetric** [larics/icuas24_competition#15]
### Discussed in https://github.com/larics/icuas24_competition/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **A4dii** January  4, 2024</sup>
After setting up the catkin_ws and cloning both uav_ros_simulation and icuas24_competition repositories, I am facing problem while running the installation script the ~/catkin_ws/src/uav_ros_simulation/installation/install.sh
Can you please suggest how to resolve this. 
![Screenshot from 2024-01-04 19-08-32](https://github.com/larics/icuas23_competition/assets/123290257/49806435-e9f9-443a-ac0a-1e2bafbd33ca)
</div>

**Comment by fpetric** [comment]
This looks similar to #14, we are looking into it.

**Comment by lmark1** [comment]
The native installation of **uav_ros_simulation** is no longer available due to restricted permissions to certain repositories.
The preferred and easiest method is to simply build the Docker (in **icuas24_competition** repository) by running
```bash
./docker_build.sh
```
