### ISSUE TITLE
I used the docker method here and yet I'm getting the same error as when doing it with the manual method

### ISSUE THREAD

**Issue by vialbruh** [larics/icuas24_competition#16]
![Screenshot from 2024-01-06 19-24-04](https://github.com/larics/icuas24_competition/assets/149217318/59847351-553b-4da1-bd6f-c06b242fdba7)

**Comment by lmark1** [comment]
To build and run the Docker image please use the following commands:
```bash
./docker_build.sh
./docker_run.sh
```

After this you should be inside the docker container and you can start the challenge by running:
```bash
./start.sh
```
