### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by joaovmamute** [larics/icuas24_competition#2]
Greetings, I started following the README.md, but in the "Install" section I can't access the link https://github.com/larics/uav_ros_simulation, and when I run the command: `curl https://raw.githubusercontent.com/larics/uav_ros_simulation/main/installation/dependencies/docker.sh | bash` I get 404 error

**Comment by fpetric** [comment]
Something broke on our end, we made things private so people are not stuck with defective installation. We are working on it.
