### ISSUE TITLE
Will the obstacle CHANGE or NOT

### ISSUE THREAD

**Issue by allenthreee** [larics/icuas24_competition#3]
Hello, as the title, will the size and locations of the garden beds change every single RUN, or they remain the same, and only the fruits changes？

**Comment by fpetric** [comment]
Hi, 

the layout stays the same. The only change is the location (which garden beds have tomatoes and which has peppers...) and number of plants (are there one, two or three plants in the bed), and location and number of fruits on those plants.

**Comment by allenthreee** [comment]
Get it, thank you for your kindly reply.
