### ISSUE TITLE
Dockerized environment functions properly after first startup (first build) but on system restart it no longer outputs gazebo

### ISSUE THREAD

**Issue by Jimmeimetis** [larics/icuas24_competition#30]
Hi,

We are experiencing the issue mentioned in the title. Our system uses ubuntu 18.04 and docker in which the icuas24 competition is running using the focal version( everything default).

The 18.04 installation is brand new and everything installed correctly using your scripts. After cleaning docker (images,volumes,containers) and installing again the issue fixes itself but on restart gazebo fails to output image(no window at all).

Anyone else experiencing this?

**Comment by fpetric** [comment]
This looks like xauth issue with docker. If I understand correctly, when you do a clean image build and first container run, then everything works as intended, and if you restart your host machine, it breaks? What happens when you stop the container and try to start it (before restarting the host machine) (docker start -i <container_name>)?

**Comment by Jimmeimetis** [comment]
Went to replicate the issue and it works now. Did sudo on all .sh files and for this time at least it works. +1 on the issue being xauth related.

Completed the code required for the intermediate submission in the form of a single python file. Now all that is left is to figure out the how to package this with docker. Thanks for the quick reply!

**Comment by fpetric** [comment]
If you have just a single python file without additional dependencies, you can just add it to your local copy of this repo, add the appropriate lines in session.yml file to run it, and just zip the repo up. We will then run build script on our end, and your file will be copied to the container along all other files.
