### ISSUE TITLE
start position

### ISSUE THREAD

**Issue by tanz-nwpu** [larics/icuas24_competition#31]
Hi,
In the The Intermediate submission - deadline, instructions, it said _UAV should spawn at the location x=1, y=1,_. While in [1](https://github.com/larics/icuas24_competition/blob/7fbaa49585ea6114466409d6901b4c1c60efee87/startup/challenge/session.yml#L26), the UAV is spawned at (1.5, 1.5, 0), after it take off, the position is (2,2,2). Should we change this?

**Comment by fpetric** [comment]
Yes.

**Comment by tanz-nwpu** [comment]
> Yes.

We are still confused: should we manually adjust the `x:=1.5 y:=1.5` to `x:=1 y:=1` in the `session.yml` file, or should we alter our position to allow the UAV to fly to the coordinates `(1, 1, z)`? Is this position determined by odometry? This question arises even if the position we set does not match the position displayed in Gazebo's odometry.

**Comment by fpetric** [comment]
You should adjust session file. I will check, I think we resolved this discrepancy between gazebo and odometry at some point. But for this submission, it is not that important

**Comment by allenthreee** [comment]
> You should adjust session file. I will check, I think we resolved this discrepancy between gazebo and odometry at some point. But for this submission, it is not that important

Hi, Frano,
Thank you for your swift reply. Our concern is that if there is a bias between the init pose and the odometry ouput(differences in README and code), the UAV might hit the obstacle if some setting is changed and others are not changed accordingly. So we want to ensure these parameters are set correctly :)
