### ISSUE TITLE
Access the UAV's battery value

### ISSUE THREAD

**Issue by joaovmamute** [larics/icuas24_competition#35]
Greetings,

To improve our optimization, we would need to access the UAV's battery value, however using the command `rostopic echo /red/mavros/battery` is returning this error:

![image](https://github.com/larics/icuas24_competition/assets/50585081/0b845d20-bd58-4acd-a8c4-c5a8d2b8a62f)

**Comment by fpetric** [comment]
We do not simulate the battery. As stated in the rulebook, (quote: _the teams will need to minimise the path and the time taken to count the fruits_), we are looking into a measure that will encourage minimizing path length and minimizing time.
