### ISSUE TITLE
Gazebo fail after running start.sh

### ISSUE THREAD

**Issue by allenthreee** [larics/icuas24_competition#4]
The error message is as follows:

/root/sim_ws/src/uav_ros_simulation/ros_packages/ardupilot_gazebo/scripts/run_copter.sh: "cat ${PARAM_PATH} >> ${IDENTITY_PATH}" command failed with exit code 1
[sim_vehicle_startup-1] process has died [pid 26799, exit code 1, cmd bash -c sleep 1.0; $0 $@ /root/sim_ws/src/uav_ros_simulation/ros_packages/ardupilot_gazebo/scripts/run_copter.sh kopterworx 1 /root/uav_ws/install/share/icuas24_competition/parameters/arducopter_nogps.params false false 50 gazebo-iris ArduCopter false --no-rebuild __name:=sim_vehicle_startup __log:=/root/.ros/log/2ca6768a-9f10-11ee-b33f-a4c3f0785be 5/sim_vehicle_startup-1.log].
log file: /root/.ros/log/2ca6768a-9f10-11ee-b33f-a4c3f0785be5/sim_vehicle_startup-1*.log
all processes on machine have died, roslaunch will exit

![lmark1_docker_tags](https://github.com/larics/icuas24_competition/assets/59171742/14c0ad6c-c6a4-4e79-87ab-23de2a4ef0ac)
There are only these 2 tags in your dockerhub, are the previous ones deleted? And I guess the bugs are related to this docker image version :)

**Comment by fpetric** [comment]
@lmark1 can you take a look?

**Comment by lmark1** [comment]
Hey @allenthreee,

You can try now. I updated Dockerfiles and build script.

**Comment by allenthreee** [comment]
> Hey @allenthreee,
> 
> You can try now. I updated Dockerfiles and build script.

Thank you for your swift reply. The docker image works now.
However, the UAV flies out of control after the gazebo simulation starts.
The terminal output and gazebo are shown below, can you take a look :)

![uav_flies_out_of_range](https://github.com/larics/icuas24_competition/assets/59171742/96aa1e04-0d1f-42c3-9a54-e048045fce08)

![uav_flies_out_of_range_gazebo](https://github.com/larics/icuas24_competition/assets/59171742/3403f538-a8b0-4268-84a4-7b2715563992)

**Comment by lmark1** [comment]
Hey @allenthreee,

It seems that the starutup folder is using an older parameter set for ardupilot.

I will get it sorted by the end of today. 
Thank you for your patience.

**Comment by allenthreee** [comment]
> Hey @allenthreee,
> 
> It seems that the starutup folder is using an older parameter set for ardupilot.
> 
> I will get it sorted by the end of today. Thank you for your patience.

Hi, @lmark1 ,
Thank you for your help, may I ask have you upload the new params :)

**Comment by lmark1** [comment]
@allenthreee 

Please run the following command to update the base images:
```bash
docker pull lmark1/uav_ros_simulation:focal-bin-0.0.1
```

or if you're not using GPU

```bash
docker pull lmark1/uav_ros_simulation:focal-nogpu-bin-0.0.1
```

Then, run ```./docker_build.sh``` again, remove the existing icuas_competition container, and run ```./docker_run.sh```.
I tried it out and it should be running as intended, i.e. UAV takes off some time after ```./start.sh``` is started.

**Comment by lmark1** [comment]
> 
> Hi @lmark1 ,
> 
> Thank you for your help, it works perfectly now.
> 
> Merry Christmas!

Good to hear!
Merry Christmas! 😁
