### ISSUE TITLE
Inconsistent Topics in readme and Gazebo Simulation

### ISSUE THREAD

**Issue by allenthreee** [larics/icuas24_competition#7]
Following are some inconsistencies in the documentation found in our test:

1. https://github.com/larics/icuas24_competition/blob/5fd0bb53b1423d075c4b14c6ef1ea894d6e64b1e/README.md?plain=1#L134
It seems that /mavros/global_position/local is not aligned with gazebo simuation, while /red/odometry gives the pose of the UAV.

====================================================

2. https://github.com/larics/icuas24_competition/blob/5fd0bb53b1423d075c4b14c6ef1ea894d6e64b1e/README.md?plain=1#L169
In readme, the topic is called **plant_beds**, while the gazebo simulation gives "plants_beds"

**Comment by fpetric** [comment]
Hi @allenthreee, 

thanks for reporting. regarding the first issue, we will look into it. meaning @lmark1 will look into it, please? 

regarding the topic, it should be _**plant_beds**_, we will fix that.

**Comment by lmark1** [comment]
The topic names are updated. Thank you for noticing :)
