### ISSUE TITLE
Cannot control UAV generate_toppra_trajectory.py not found 

### ISSUE THREAD

**Issue by hunterls97** [larics/icuas24_competition#8]
When we try to publish to tracker/input_pose the drone does not move. We noticed the topp_tracker.launch file fails to find the generate_toppra_trajectory.py node. 
![Screenshot from 2024-01-04 13-32-45](https://github.com/larics/icuas24_competition/assets/28965111/6e6c2911-8d66-4cf0-932f-ab64e217d0b9)
we tried a full rebuild using `./docker_build.sh --build-args "--no-cache --pull" --focal ` but the issue still persists

**Comment by hunterls97** [comment]
We are able to control the UAV using the focal-nogpu image. It seems that the topp_ros package does not have any nodes in the /uav_ws/install/share/topp_ros directory for the focal image, but they are there in focal-nogpu.

**Comment by lmark1** [comment]
Please try explicitly pulling the new image as follows:
```bash
docker pull lmark1/uav_ros_simulation:focal-bin-0.0.1
```

**Comment by hunterls97** [comment]
pulled the new image, it works now. Thanks!
